// Code generated by goctl. DO NOT EDIT.
package types

type CreateTagRequest struct {
	TagName   string `json:"tagName"`
	GroupName string `json:"groupName"`
	Type      string `json:"type"`
}

type CreateTagResponse struct {
	GroupName string   `json:"groupName"`
	TagNames  []string `json:"tagNames"`
}

type TagGroupName struct {
}
