// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"Link/service/user/internal/logic/usercontactservice"
	"Link/service/user/internal/svc"
	"Link/service/user/user"
)

type UserContactServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserContactServiceServer
}

func NewUserContactServiceServer(svcCtx *svc.ServiceContext) *UserContactServiceServer {
	return &UserContactServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserContactServiceServer) UserFlowed(ctx context.Context, in *user.UserAddRequest) (*user.Empty, error) {
	l := usercontactservicelogic.NewUserFlowedLogic(ctx, s.svcCtx)
	return l.UserFlowed(in)
}

func (s *UserContactServiceServer) UserUpdateRemark(ctx context.Context, in *user.UserUpdateRemarkRequest) (*user.Empty, error) {
	l := usercontactservicelogic.NewUserUpdateRemarkLogic(ctx, s.svcCtx)
	return l.UserUpdateRemark(in)
}
