// Code generated by goctl. DO NOT EDIT.
// Source: tag.proto

package server

import (
	"Link/service/tag/internal/logic/tagloginfront"
	"Link/service/tag/internal/svc"
	"Link/service/tag/tag"
)

type TagLoginFrontServer struct {
	svcCtx *svc.ServiceContext
	tag.UnimplementedTagLoginFrontServer
}

func NewTagLoginFrontServer(svcCtx *svc.ServiceContext) *TagLoginFrontServer {
	return &TagLoginFrontServer{
		svcCtx: svcCtx,
	}
}
