version: '3'

######## 项目依赖的环境，启动项目之前要先启动此环境 #######
services:
  # 服务发现
  tag-rpc: #自定义容器名称
    build:
      context: service/tag #上下文
      dockerfile: Dockerfile #Dockerfile文件名称
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8081:8081"
    stdin_open: true #打开标准输入,可以接受外部输入
    tty: true
    networks:
      - backend
    restart: always #指定容器退出后的重启策略为始终重启
  user-rpc: #自定义容器名称
    build:
      context: service/user
      dockerfile: Dockerfile
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8082:8082"
    stdin_open: true #打开标准输入,可以接受外部输入
    tty: true
    networks:
      - backend
    restart: always #指定容器退出后的重启策略为始终重启
  #api
  tag-api:
    build:
      context: restful/tag
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    networks:
      - backend
    restart: always
  user-api:
    build:
      context: restful/user
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    ports:
      - "8887:8887"
    stdin_open: true
    tty: true
    networks:
      - backend
    restart: always
networks:
  backend:
    driver: bridge


