// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"Link/service/user/internal/logic/usergroupservice"
	"Link/service/user/internal/svc"
	"Link/service/user/user"
)

type UserGroupServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserGroupServiceServer
}

func NewUserGroupServiceServer(svcCtx *svc.ServiceContext) *UserGroupServiceServer {
	return &UserGroupServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserGroupServiceServer) UserCreateGroup(ctx context.Context, in *user.UserCreateGroupRequest) (*user.Empty, error) {
	l := usergroupservicelogic.NewUserCreateGroupLogic(ctx, s.svcCtx)
	return l.UserCreateGroup(in)
}
