// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	systmeTag "tag/restful/internal/handler/systmeTag"
	tagLogin "tag/restful/internal/handler/tagLogin"
	"tag/restful/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/selectGroupTag",
				Handler: systmeTag.SelectGroupTagHandler(serverCtx),
			},
		},
		rest.WithPrefix("/app/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createTag",
				Handler: tagLogin.CreateTagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteTag",
				Handler: tagLogin.DeleteTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/selectAllTags",
				Handler: tagLogin.SelectAllTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/selectMyTags",
				Handler: tagLogin.SelectMyTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/selectUserTagByGroup",
				Handler: tagLogin.SelectUserTagByGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateSelfTag",
				Handler: tagLogin.UpdateSelfTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/app/tag"),
	)
}
