// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package chatservice

import (
	"context"

	"chat/service/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                    = chat.Empty
	GetOfflineMessageRequest = chat.GetOfflineMessageRequest
	Message                  = chat.Message
	Messages                 = chat.Messages
	SaveGroupMessageRequest  = chat.SaveGroupMessageRequest
	SaveMessageRequest       = chat.SaveMessageRequest

	ChatService interface {
		SaveOfflineMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*Empty, error)
		GetOfflineMessage(ctx context.Context, in *GetOfflineMessageRequest, opts ...grpc.CallOption) (*Messages, error)
		SaveGroupMessage(ctx context.Context, in *SaveGroupMessageRequest, opts ...grpc.CallOption) (*Empty, error)
		SaveGroupMessageRedis(ctx context.Context, in *SaveGroupMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

func (m *defaultChatService) SaveOfflineMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.SaveOfflineMessage(ctx, in, opts...)
}

func (m *defaultChatService) GetOfflineMessage(ctx context.Context, in *GetOfflineMessageRequest, opts ...grpc.CallOption) (*Messages, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetOfflineMessage(ctx, in, opts...)
}

func (m *defaultChatService) SaveGroupMessage(ctx context.Context, in *SaveGroupMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.SaveGroupMessage(ctx, in, opts...)
}

func (m *defaultChatService) SaveGroupMessageRedis(ctx context.Context, in *SaveGroupMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.SaveGroupMessageRedis(ctx, in, opts...)
}
