// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"chat/service/chat"
	"chat/service/internal/logic"
	"chat/service/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServiceServer) SaveOfflineMessage(ctx context.Context, in *chat.SaveMessageRequest) (*chat.Empty, error) {
	l := logic.NewSaveOfflineMessageLogic(ctx, s.svcCtx)
	return l.SaveOfflineMessage(in)
}

func (s *ChatServiceServer) GetOfflineMessage(ctx context.Context, in *chat.GetOfflineMessageRequest) (*chat.Messages, error) {
	l := logic.NewGetOfflineMessageLogic(ctx, s.svcCtx)
	return l.GetOfflineMessage(in)
}

func (s *ChatServiceServer) SaveGroupMessage(ctx context.Context, in *chat.SaveGroupMessageRequest) (*chat.Empty, error) {
	l := logic.NewSaveGroupMessageLogic(ctx, s.svcCtx)
	return l.SaveGroupMessage(in)
}

func (s *ChatServiceServer) SaveGroupMessageRedis(ctx context.Context, in *chat.SaveGroupMessageRequest) (*chat.Empty, error) {
	l := logic.NewSaveGroupMessageRedisLogic(ctx, s.svcCtx)
	return l.SaveGroupMessageRedis(in)
}
