// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	tagLogin "Link/restful/tag/internal/handler/tagLogin"
	"Link/restful/tag/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createTag",
				Handler: tagLogin.CreateTagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/selectGroupTag",
				Handler: tagLogin.SelectGourpTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/app/tag"),
	)
}
