version: '3'

networks:
  backend:
    driver: bridge


######## 项目依赖的环境，启动项目之前要先启动此环境 #######
services:
  etcd:
    build:
      context: etcd
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://101.37.175.145:2379
    ports: # 设置端口映射
      - "2379:2379"
    networks:
      - backend
    restart: always
  etcd-manage:
    build:
      context: etcd-manage
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7000:8080"                    # 设置容器8080端口映射指定宿主机端口，用于宿主机访问可视化web
    depends_on:                                       # 依赖容器
      - etcd                                          # 在 etcd 服务容器启动后启动
    networks:
      - backend
    restart: always
  # 服务发现
  tag-rpc: #自定义容器名称
    image: tag-rpc:0.0.1
    container_name: tag-rpc
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8081:8081"
    networks:
      - backend

  user-rpc: #自定义容器名称
    image: user-rpc:0.0.1
    container_name: user-rpc
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8082:8082"
    networks:
      - backend

  tag-api: #自定义容器名称
    image: tag-api:0.0.1
    container_name: tag-api
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8888:8888"
    networks:
      - backend

  user-api: #自定义容器名称
    image: user-api:0.0.1
    container_name: user-api
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8887:8887"
    networks:
      - backend

