version: '3'

networks:
  backend:
    driver: bridge


######## 项目依赖的环境，启动项目之前要先启动此环境 #######
services:
  # 服务发现
  tag-rpc: #自定义容器名称
    image: tag-rpc:0.0.1
    container_name: tag-rpc
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8081:8081"
    networks:
      - backend

  user-rpc: #自定义容器名称
    image: user-rpc:0.0.1
    container_name: user-rpc
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8082:8082"
    networks:
      - backend

  tag-api: #自定义容器名称
    image: tag-api:0.0.1
    container_name: tag-api
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8888:8888"
    networks:
      - backend

  user-api: #自定义容器名称
    image: user-api:0.0.2
    container_name: user-api
    restart: always
    environment: #设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: #设置端口映射
      - "8887:8887"
    networks:
      - backend

