// Code generated by goctl. DO NOT EDIT.
// Source: tag.proto

package server

import (
	"context"

	"Link/service/tag/internal/logic/tagsign"
	"Link/service/tag/internal/svc"
	"Link/service/tag/tag"
)

type TagSignServer struct {
	svcCtx *svc.ServiceContext
	tag.UnimplementedTagSignServer
}

func NewTagSignServer(svcCtx *svc.ServiceContext) *TagSignServer {
	return &TagSignServer{
		svcCtx: svcCtx,
	}
}

func (s *TagSignServer) SignUserChooseTag(ctx context.Context, in *tag.UserChooseTagRequest) (*tag.UserChooseTagRequest, error) {
	l := tagsignlogic.NewSignUserChooseTagLogic(ctx, s.svcCtx)
	return l.SignUserChooseTag(in)
}
