// Code generated by goctl. DO NOT EDIT.
// Source: tag.proto

package tagclient

import (
	"context"

	"Link/service/tag/tag"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = tag.Request
	Response = tag.Response

	Tag interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTag struct {
		cli zrpc.Client
	}
)

func NewTag(cli zrpc.Client) Tag {
	return &defaultTag{
		cli: cli,
	}
}

func (m *defaultTag) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := tag.NewTagClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
