// Code generated by goctl. DO NOT EDIT.
package types

type CreateTagRequest struct {
	TagName   string `json:"tagName" validate:"required"`
	GroupName string `json:"groupName" validate:"required"`
	Type      string `json:"type" validate:"required"`
}

type CreateTagResponse struct {
	GroupName    string         `json:"groupName"`
	TagGroupName []TagGroupName `json:"tagGroupName"`
}

type SelectAllTagsResponse struct {
	GroupNameId int64  `json:"groupNameId"`
	GroupName   string `json:"groupName"`
	Tags        []Tag  `json:"tags"`
}

type SelectMyTagsResponse struct {
	Id        uint64 `json:"id"`
	TagName   string `json:"tagName"`
	GroupName string `json:"groupName"`
}

type Tag struct {
	TagId     uint64 `json:"tagId"`
	CreatorId uint64 `json:"creatorId"`
	TagName   string `json:"groupName"`
}

type TagGroupName struct {
	GroupNameId int    `json:"groupNameId"`
	Creator     int    `json:"creator"`
	GroupName   string `json:"groupName"`
}

type DelteTags struct {
	TagIds []uint64 `json:"tagIds" validate:"required"`
}

type SelectUserTagByGroupRequest struct {
	GroupName string `json:"groupName" validate:"required"`
}

type SelectUserTagByGroupResponse struct {
	GroupName string `json:"groupName"`
	Tags      []Tag  `json:"tags"`
}

type UpdateSelfTagRequest struct {
	GroupName string `json:"groupName" validate:"required"`
	TagName   string `json:"tagName" validate:"required"`
	OldName   string `json:"oldName" validate:"required"`
}
