// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: app/tag/service/tag.proto

package tag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{0}
}

// CreateTagRequest创建标签 start
type CreateTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId  uint64 `protobuf:"varint,1,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	TagName    string `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	GroupName  string `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	OldTagName string `protobuf:"bytes,5,opt,name=old_tagName,json=oldTagName,proto3" json:"old_tagName,omitempty"`
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *CreateTagRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateTagRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTagRequest) GetOldTagName() string {
	if x != nil {
		return x.OldTagName
	}
	return ""
}

type CreateTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	// 使用 repeated 关键字表示 LowTags 是一个切片
	LowTags []*CreateTagResponse_LowTags `protobuf:"bytes,3,rep,name=low_tags,json=lowTags,proto3" json:"low_tags,omitempty"`
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateTagResponse) GetLowTags() []*CreateTagResponse_LowTags {
	if x != nil {
		return x.LowTags
	}
	return nil
}

// 删除标签 start
type DeleteTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId uint64   `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	TagId     []uint64 `protobuf:"varint,2,rep,packed,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTagRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *DeleteTagRequest) GetTagId() []uint64 {
	if x != nil {
		return x.TagId
	}
	return nil
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{4}
}

// 查询全部标签组 start
type GroupTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *GroupTag) Reset() {
	*x = GroupTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTag) ProtoMessage() {}

func (x *GroupTag) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTag.ProtoReflect.Descriptor instead.
func (*GroupTag) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{5}
}

func (x *GroupTag) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupTag) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type GroupTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*GroupTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *GroupTagResponse) Reset() {
	*x = GroupTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTagResponse) ProtoMessage() {}

func (x *GroupTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTagResponse.ProtoReflect.Descriptor instead.
func (*GroupTagResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{6}
}

func (x *GroupTagResponse) GetTags() []*GroupTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 根据所选标签组 查询对应小标签
type SelectAllTagsByGroupName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupAme string `protobuf:"bytes,1,opt,name=group_ame,json=groupAme,proto3" json:"group_ame,omitempty"`
}

func (x *SelectAllTagsByGroupName) Reset() {
	*x = SelectAllTagsByGroupName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectAllTagsByGroupName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAllTagsByGroupName) ProtoMessage() {}

func (x *SelectAllTagsByGroupName) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAllTagsByGroupName.ProtoReflect.Descriptor instead.
func (*SelectAllTagsByGroupName) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{7}
}

func (x *SelectAllTagsByGroupName) GetGroupAme() string {
	if x != nil {
		return x.GroupAme
	}
	return ""
}

type AllTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagName   string `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	GroupName string `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	CreatorId uint64 `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
}

func (x *AllTags) Reset() {
	*x = AllTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTags) ProtoMessage() {}

func (x *AllTags) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTags.ProtoReflect.Descriptor instead.
func (*AllTags) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{8}
}

func (x *AllTags) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AllTags) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *AllTags) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AllTags) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type AllTagsByGroupNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowTags []*AllTags `protobuf:"bytes,1,rep,name=low_tags,json=lowTags,proto3" json:"low_tags,omitempty"`
}

func (x *AllTagsByGroupNameResponse) Reset() {
	*x = AllTagsByGroupNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTagsByGroupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTagsByGroupNameResponse) ProtoMessage() {}

func (x *AllTagsByGroupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTagsByGroupNameResponse.ProtoReflect.Descriptor instead.
func (*AllTagsByGroupNameResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{9}
}

func (x *AllTagsByGroupNameResponse) GetLowTags() []*AllTags {
	if x != nil {
		return x.LowTags
	}
	return nil
}

// 用户选择自定义标签以及系统标签
type ChooseTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                              //用户id
	SystemId uint64   `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`  //系统标签id
	TagIds   []uint64 `protobuf:"varint,3,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"` //用户自定义标签id
}

func (x *ChooseTagsRequest) Reset() {
	*x = ChooseTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseTagsRequest) ProtoMessage() {}

func (x *ChooseTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseTagsRequest.ProtoReflect.Descriptor instead.
func (*ChooseTagsRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{10}
}

func (x *ChooseTagsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChooseTagsRequest) GetSystemId() uint64 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *ChooseTagsRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type ChooseTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChooseTagsResponse) Reset() {
	*x = ChooseTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseTagsResponse) ProtoMessage() {}

func (x *ChooseTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseTagsResponse.ProtoReflect.Descriptor instead.
func (*ChooseTagsResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{11}
}

// 查询当前用户选择以及创建的标签 Request
type SelectLinkTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //用户id
}

func (x *SelectLinkTagsRequest) Reset() {
	*x = SelectLinkTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectLinkTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectLinkTagsRequest) ProtoMessage() {}

func (x *SelectLinkTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectLinkTagsRequest.ProtoReflect.Descriptor instead.
func (*SelectLinkTagsRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{12}
}

func (x *SelectLinkTagsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询当前用户选择以及创建的标签 Response
type SelectLinkTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                //标签id
	CreatorId uint64 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"` //创作者id
	TagName   string `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`        //标签名称
}

func (x *SelectLinkTag) Reset() {
	*x = SelectLinkTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectLinkTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectLinkTag) ProtoMessage() {}

func (x *SelectLinkTag) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectLinkTag.ProtoReflect.Descriptor instead.
func (*SelectLinkTag) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{13}
}

func (x *SelectLinkTag) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelectLinkTag) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *SelectLinkTag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type SelectLinkTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkTags []*SelectLinkTag `protobuf:"bytes,1,rep,name=linkTags,proto3" json:"linkTags,omitempty"` //数据
}

func (x *SelectLinkTagsResponse) Reset() {
	*x = SelectLinkTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectLinkTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectLinkTagsResponse) ProtoMessage() {}

func (x *SelectLinkTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectLinkTagsResponse.ProtoReflect.Descriptor instead.
func (*SelectLinkTagsResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{14}
}

func (x *SelectLinkTagsResponse) GetLinkTags() []*SelectLinkTag {
	if x != nil {
		return x.LinkTags
	}
	return nil
}

// 查询我创建的标签
type SelectMyTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //用户id
}

func (x *SelectMyTagsRequest) Reset() {
	*x = SelectMyTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectMyTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMyTagsRequest) ProtoMessage() {}

func (x *SelectMyTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMyTagsRequest.ProtoReflect.Descriptor instead.
func (*SelectMyTagsRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{15}
}

func (x *SelectMyTagsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 检查标签数量
type CheckTagCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //当前登录用户的id
}

func (x *CheckTagCountRequest) Reset() {
	*x = CheckTagCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTagCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTagCountRequest) ProtoMessage() {}

func (x *CheckTagCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTagCountRequest.ProtoReflect.Descriptor instead.
func (*CheckTagCountRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{16}
}

func (x *CheckTagCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckTagCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` //标签数
}

func (x *CheckTagCountResponse) Reset() {
	*x = CheckTagCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTagCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTagCountResponse) ProtoMessage() {}

func (x *CheckTagCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTagCountResponse.ProtoReflect.Descriptor instead.
func (*CheckTagCountResponse) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{17}
}

func (x *CheckTagCountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 取消选择标签
type CancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagIds []uint64 `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{18}
}

func (x *CancelRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type UserChooseTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId  uint64 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *UserChooseTagRequest) Reset() {
	*x = UserChooseTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChooseTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChooseTagRequest) ProtoMessage() {}

func (x *UserChooseTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChooseTagRequest.ProtoReflect.Descriptor instead.
func (*UserChooseTagRequest) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{19}
}

func (x *UserChooseTagRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserChooseTagRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CreateTagResponse_LowTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId uint64 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	TagName   string `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
}

func (x *CreateTagResponse_LowTags) Reset() {
	*x = CreateTagResponse_LowTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_tag_service_tag_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagResponse_LowTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse_LowTags) ProtoMessage() {}

func (x *CreateTagResponse_LowTags) ProtoReflect() protoreflect.Message {
	mi := &file_app_tag_service_tag_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse_LowTags.ProtoReflect.Descriptor instead.
func (*CreateTagResponse_LowTags) Descriptor() ([]byte, []int) {
	return file_app_tag_service_tag_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateTagResponse_LowTags) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTagResponse_LowTags) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateTagResponse_LowTags) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

var File_app_tag_service_tag_proto protoreflect.FileDescriptor

var file_app_tag_service_tag_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x61, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x61, 0x67,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x6c,
	0x64, 0x5f, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x6c, 0x64, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc2, 0x01, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x39, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x77, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x07, 0x6c, 0x6f, 0x77, 0x54, 0x61, 0x67, 0x73, 0x1a, 0x53, 0x0a, 0x07, 0x4c,
	0x6f, 0x77, 0x54, 0x61, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x48, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x39, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x10, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x37, 0x0a, 0x18, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x61,
	0x67, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6d, 0x65, 0x22, 0x72, 0x0a, 0x07, 0x41, 0x6c,
	0x6c, 0x54, 0x61, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x45,
	0x0a, 0x1a, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08,
	0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x52, 0x07, 0x6c, 0x6f,
	0x77, 0x54, 0x61, 0x67, 0x73, 0x22, 0x59, 0x0a, 0x11, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x67, 0x49, 0x64, 0x73,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x59, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x16, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b,
	0x54, 0x61, 0x67, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x79,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x67,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61,
	0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x06, 0x74, 0x61, 0x67, 0x49, 0x64, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x32,
	0x99, 0x05, 0x0a, 0x08, 0x54, 0x61, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x67, 0x12, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61,
	0x67, 0x12, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54,
	0x61, 0x67, 0x12, 0x0a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41,
	0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67,
	0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x1f, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x0a, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x73, 0x12, 0x16, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1a,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x67,
	0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x4d, 0x79, 0x54, 0x61, 0x67, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x4d, 0x79, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x42,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x67, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54,
	0x61, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x67, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0d, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x12, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xa5, 0x01, 0x0a, 0x07,
	0x54, 0x61, 0x67, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x49, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x12, 0x19, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4f, 0x0a, 0x17, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68,
	0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x12, 0x19, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x74, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_tag_service_tag_proto_rawDescOnce sync.Once
	file_app_tag_service_tag_proto_rawDescData = file_app_tag_service_tag_proto_rawDesc
)

func file_app_tag_service_tag_proto_rawDescGZIP() []byte {
	file_app_tag_service_tag_proto_rawDescOnce.Do(func() {
		file_app_tag_service_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_tag_service_tag_proto_rawDescData)
	})
	return file_app_tag_service_tag_proto_rawDescData
}

var file_app_tag_service_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_app_tag_service_tag_proto_goTypes = []interface{}{
	(*Empty)(nil),                      // 0: tag.Empty
	(*CreateTagRequest)(nil),           // 1: tag.CreateTagRequest
	(*CreateTagResponse)(nil),          // 2: tag.CreateTagResponse
	(*DeleteTagRequest)(nil),           // 3: tag.DeleteTagRequest
	(*DeleteTagResponse)(nil),          // 4: tag.DeleteTagResponse
	(*GroupTag)(nil),                   // 5: tag.GroupTag
	(*GroupTagResponse)(nil),           // 6: tag.GroupTagResponse
	(*SelectAllTagsByGroupName)(nil),   // 7: tag.SelectAllTagsByGroupName
	(*AllTags)(nil),                    // 8: tag.AllTags
	(*AllTagsByGroupNameResponse)(nil), // 9: tag.AllTagsByGroupNameResponse
	(*ChooseTagsRequest)(nil),          // 10: tag.ChooseTagsRequest
	(*ChooseTagsResponse)(nil),         // 11: tag.ChooseTagsResponse
	(*SelectLinkTagsRequest)(nil),      // 12: tag.SelectLinkTagsRequest
	(*SelectLinkTag)(nil),              // 13: tag.SelectLinkTag
	(*SelectLinkTagsResponse)(nil),     // 14: tag.SelectLinkTagsResponse
	(*SelectMyTagsRequest)(nil),        // 15: tag.SelectMyTagsRequest
	(*CheckTagCountRequest)(nil),       // 16: tag.CheckTagCountRequest
	(*CheckTagCountResponse)(nil),      // 17: tag.CheckTagCountResponse
	(*CancelRequest)(nil),              // 18: tag.CancelRequest
	(*UserChooseTagRequest)(nil),       // 19: tag.UserChooseTagRequest
	(*CreateTagResponse_LowTags)(nil),  // 20: tag.CreateTagResponse.LowTags
}
var file_app_tag_service_tag_proto_depIdxs = []int32{
	20, // 0: tag.CreateTagResponse.low_tags:type_name -> tag.CreateTagResponse.LowTags
	5,  // 1: tag.GroupTagResponse.tags:type_name -> tag.GroupTag
	8,  // 2: tag.AllTagsByGroupNameResponse.low_tags:type_name -> tag.AllTags
	13, // 3: tag.SelectLinkTagsResponse.linkTags:type_name -> tag.SelectLinkTag
	1,  // 4: tag.TagLogin.CreateTag:input_type -> tag.CreateTagRequest
	1,  // 5: tag.TagLogin.UpdateTag:input_type -> tag.CreateTagRequest
	3,  // 6: tag.TagLogin.DeleteTag:input_type -> tag.DeleteTagRequest
	0,  // 7: tag.TagLogin.SelectGroupTag:input_type -> tag.Empty
	7,  // 8: tag.TagLogin.SelectAllTagsByGroup:input_type -> tag.SelectAllTagsByGroupName
	10, // 9: tag.TagLogin.ChooseTags:input_type -> tag.ChooseTagsRequest
	12, // 10: tag.TagLogin.SelectLinkTags:input_type -> tag.SelectLinkTagsRequest
	15, // 11: tag.TagLogin.SelectMyTags:input_type -> tag.SelectMyTagsRequest
	16, // 12: tag.TagLogin.CheckTagCount:input_type -> tag.CheckTagCountRequest
	18, // 13: tag.TagLogin.CancelUserTag:input_type -> tag.CancelRequest
	19, // 14: tag.TagSign.SignUserChooseTag:input_type -> tag.UserChooseTagRequest
	19, // 15: tag.TagSign.SignUserChooseTagRevert:input_type -> tag.UserChooseTagRequest
	2,  // 16: tag.TagLogin.CreateTag:output_type -> tag.CreateTagResponse
	2,  // 17: tag.TagLogin.UpdateTag:output_type -> tag.CreateTagResponse
	4,  // 18: tag.TagLogin.DeleteTag:output_type -> tag.DeleteTagResponse
	6,  // 19: tag.TagLogin.SelectGroupTag:output_type -> tag.GroupTagResponse
	9,  // 20: tag.TagLogin.SelectAllTagsByGroup:output_type -> tag.AllTagsByGroupNameResponse
	11, // 21: tag.TagLogin.ChooseTags:output_type -> tag.ChooseTagsResponse
	14, // 22: tag.TagLogin.SelectLinkTags:output_type -> tag.SelectLinkTagsResponse
	9,  // 23: tag.TagLogin.SelectMyTags:output_type -> tag.AllTagsByGroupNameResponse
	17, // 24: tag.TagLogin.CheckTagCount:output_type -> tag.CheckTagCountResponse
	0,  // 25: tag.TagLogin.CancelUserTag:output_type -> tag.Empty
	19, // 26: tag.TagSign.SignUserChooseTag:output_type -> tag.UserChooseTagRequest
	19, // 27: tag.TagSign.SignUserChooseTagRevert:output_type -> tag.UserChooseTagRequest
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_tag_service_tag_proto_init() }
func file_app_tag_service_tag_proto_init() {
	if File_app_tag_service_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_tag_service_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectAllTagsByGroupName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTagsByGroupNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectLinkTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectLinkTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectLinkTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectMyTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTagCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTagCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChooseTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_tag_service_tag_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagResponse_LowTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_tag_service_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_app_tag_service_tag_proto_goTypes,
		DependencyIndexes: file_app_tag_service_tag_proto_depIdxs,
		MessageInfos:      file_app_tag_service_tag_proto_msgTypes,
	}.Build()
	File_app_tag_service_tag_proto = out.File
	file_app_tag_service_tag_proto_rawDesc = nil
	file_app_tag_service_tag_proto_goTypes = nil
	file_app_tag_service_tag_proto_depIdxs = nil
}
