// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}


type Message struct {
	From uint64 `json:"from"`
	To uint64 `json:"to"`
	Content string `json:"content"`
	Model uint `json:"model"` // 0 单聊 1 群聊
}