// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package usergroupservice

import (
	"context"

	"Link/service/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                   = user.Empty
	UserAddRequest          = user.UserAddRequest
	UserCreateGroupRequest  = user.UserCreateGroupRequest
	UserCreateRequest       = user.UserCreateRequest
	UserCreateResponse      = user.UserCreateResponse
	UserInfoRequest         = user.UserInfoRequest
	UserInfoResponse        = user.UserInfoResponse
	UserLoginRequest        = user.UserLoginRequest
	UserLoginResponse       = user.UserLoginResponse
	UserUpdateInfoRequest   = user.UserUpdateInfoRequest
	UserUpdateRemarkRequest = user.UserUpdateRemarkRequest

	UserGroupService interface {
		UserCreateGroup(ctx context.Context, in *UserCreateGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultUserGroupService struct {
		cli zrpc.Client
	}
)

func NewUserGroupService(cli zrpc.Client) UserGroupService {
	return &defaultUserGroupService{
		cli: cli,
	}
}

func (m *defaultUserGroupService) UserCreateGroup(ctx context.Context, in *UserCreateGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserGroupServiceClient(m.cli.Conn())
	return client.UserCreateGroup(ctx, in, opts...)
}
